### ISSUE TITLE
2 minor suggestions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/catch-the-dots-scratch2#5]
step 4
<img width="835" alt="step4" src="https://user-images.githubusercontent.com/28529272/54743546-4e3bfd80-4bbc-11e9-89a7-10f14bd9ed16.png">

The first image here shows the blue dot selected, but the text says to change the code of the yellow sprite.
___
Bottom of step 3:
<img width="859" alt="step3" src="https://user-images.githubusercontent.com/28529272/54743544-4e3bfd80-4bbc-11e9-9ec0-6a360d45faf1.png">

I think this sentence is too long. How about reformatting to the following?

Test your game to make sure that:
1. You lose a life if you don’t match a dot with the correct colour
**and**
1. You score a point if you match a dot correctly

(same for Scratch 3 version https://github.com/raspberrypilearning/catch-the-dots/blob/master/en/step_3.md)

**Comment by martinohanlon** [comment]
Resolved with https://github.com/raspberrypilearning/catch-the-dots-scratch2/pull/6

**Comment by martinohanlon** [comment]
and https://github.com/raspberrypilearning/catch-the-dots/pull/30
